apiVersion: v1
kind: Service
metadata:
  name: nodered-service
  namespace: node-red
spec:
  selector:
    app: nodered
  type: NodePort # Specifies the type of service as NodePort
  ports:
  - name: http
    port: 1880 # Port exposed by the service
    targetPort: 1880 # Port on which Node-RED is listening
    nodePort: 30001 # Port on the node to expose the service
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodered-deployment
  namespace: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  serviceName: "nodered-service"
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: nodered/node-red
          ports:
            - containerPort: 1880
          volumeMounts:
            - name: nodered-data
              mountPath: /data
      volumes:
        - name: nodered-data
          emptyDir: {}
