apiVersion: v1
kind: Secret
metadata:
    name: couchdb-secret
    namespace: couchdb
type: Opaque
data:
    couchdb-root-username: dXNlcm5hbWU= # username
    couchdb-root-password: cGFzc3dvcmQ= # password
