apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
  namespace: couchdb
spec:
  selector:
    app: couchdb
  ports:
    - protocol: TCP
      port: 5984
      targetPort: 5984
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb-deployment
  labels:
    app: couchdb
  namespace: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  serviceName: "couchdb-service"
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb
        ports:
        - containerPort: 5984
        env:
        - name: COUCHDB_USER
          valueFrom:
            secretKeyRef:
              name: couchdb-secret
              key: couchdb-root-username
        - name: COUCHDB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: couchdb-secret
              key: couchdb-root-password
        volumeMounts:
            - name: couchdb-data
              mountPath: /data
      volumes:
        - name: couchdb-data
          emptyDir: {}

